<?php
require_once __DIR__.'/classes/Autoload.class.php';require_once __DIR__.'/dompdf/autoload.inc.php';
use Dompdf\Dompdf;use Dompdf\Options;
$pdo=MySQL_PDO::conexao();$opc=new Opcoes();$acesso=new acesso_localizacoes();$condutor=(int)($_GET['condutor']??0);
$di=$_GET['data_inicio']??date('Y-m-d');$df=$_GET['data_fim']??$di;$hi=$_GET['hora_inicio']??'00:00';$hf=$_GET['hora_fim']??'23:59';
$logs=$acesso->listarDados($pdo,$condutor,$di.' '.$hi.':00',$df.' '.$hf.':59',5000);$nome=count($logs)?$logs[0]->getCondutorNome():'Condutor';
$rows='';foreach($logs as $l){$rows.='<tr><td>'.$l->getId().'</td><td>'.$l->getLatitude().'</td><td>'.$l->getLongitude().'</td><td>'.htmlspecialchars((string)$l->getVelocidade()).' km/h</td><td>'.$opc->inverteDateTime($l->getDtCadastro()).'</td></tr>';}
$html='<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:28px}body{font-family:DejaVu Sans,sans-serif;color:#25272b;font-size:10px}h1{font-size:20px;margin:0 0 4px}.meta{color:#6b7280;margin-bottom:18px}.summary{background:#f3f4f6;padding:10px;margin-bottom:15px}table{width:100%;border-collapse:collapse}th{background:#303236;color:#fff}th,td{padding:6px;border:1px solid #ddd;text-align:left}tr:nth-child(even){background:#f8f8f8}.footer{margin-top:12px;color:#777}</style></head><body><h1>Logs de rastreamento</h1><div class="meta">'.htmlspecialchars($nome).' - '.htmlspecialchars($di.' '.$hi).' até '.htmlspecialchars($df.' '.$hf).'</div><div class="summary"><strong>'.count($logs).'</strong> pontos encontrados. O relatório contém somente um condutor.</div><table><thead><tr><th>ID</th><th>Latitude</th><th>Longitude</th><th>Velocidade</th><th>Data/Hora</th></tr></thead><tbody>'.$rows.'</tbody></table><div class="footer">Gerado em '.date('d/m/Y H:i:s').' - OK MotoBoy Express</div></body></html>';
$opt=new Options();$opt->set('isRemoteEnabled',false);$pdf=new Dompdf($opt);$pdf->loadHtml($html,'UTF-8');$pdf->setPaper('A4','landscape');$pdf->render();$pdf->stream('logs-rastreamento-'.$condutor.'.pdf',array('Attachment'=>false));
