<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<header class="topbar"><button class="icon-button mobile-menu-button" id="mobileMenuButton" type="button" aria-label="Abrir menu" aria-controls="sidebar"><svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><div><p class="eyebrow">Configurações</p><h1>Logs de rastreamento</h1></div></header>
<section class="page-body tracking-page">
<form method="get" class="tracking-filters"><div class="form-field"><label>Condutor *</label><select name="condutor" required><option value="">Selecione um condutor</option>{foreach $condutores as $c}<option value="{$c.con_id}" {if $condutor_selecionado==$c.con_id}selected{/if}>{$c.con_nome|escape} - {$c.con_placa|escape}</option>{/foreach}</select></div>
<div class="form-field"><label>Data inicial</label><input type="date" name="data_inicio" value="{$data_inicio}"></div><div class="form-field"><label>Hora inicial</label><input type="time" name="hora_inicio" value="{$hora_inicio}"></div>
<div class="form-field"><label>Data final</label><input type="date" name="data_fim" value="{$data_fim}"></div><div class="form-field"><label>Hora final</label><input type="time" name="hora_fim" value="{$hora_fim}"></div>
<button class="primary-button" type="submit">Filtrar trajeto</button></form>
<div class="tracking-actions"><div><strong>{$nome_condutor|default:'Selecione um condutor'|escape}</strong><span>{$data_inicio|date_format:"%d/%m/%Y"} {$hora_inicio} até {$data_fim|date_format:"%d/%m/%Y"} {$hora_fim}</span></div>
<a class="secondary-button button-link" target="_blank" href="logs_rastreamento_pdf.php?condutor={$condutor_selecionado}&data_inicio={$data_inicio}&data_fim={$data_fim}&hora_inicio={$hora_inicio}&hora_fim={$hora_fim}">Exportar PDF</a></div>
<div class="tracking-stats"><article><span>Pontos encontrados</span><strong>{$total_logs}</strong></article><article><span>Velocidade média</span><strong>{$velocidade_media} km/h</strong></article><article><span>Primeiro registro</span><strong>{if $total_logs}{$primeiro_log.data}{else}—{/if}</strong></article><article><span>Último registro</span><strong>{if $total_logs}{$ultimo_log.data}{else}—{/if}</strong></article></div>
<article class="tracking-map-card"><div class="dashboard-section-title"><div><p class="eyebrow">Trajeto</p><h2>Mapa do período</h2></div></div><div id="trackingMap"></div><script id="trackingPoints" type="application/json">{$pontos_json nofilter}</script></article>
<article class="table-card"><div class="table-toolbar"><strong>Registros encontrados</strong><span class="table-result-count">Máximo exibido: 5.000 pontos</span></div><div class="table-scroll"><table class="data-table tracking-table"><thead><tr><th>ID</th><th>Condutor</th><th>Latitude</th><th>Longitude</th><th>Velocidade</th><th>Data e hora</th></tr></thead><tbody>{if $total_logs}{foreach $logs as $l}<tr><td>#{$l.id}</td><td>{$l.condutor|escape}</td><td>{$l.latitude}</td><td>{$l.longitude}</td><td>{$l.velocidade|default:'0'} km/h</td><td>{$l.data}</td></tr>{/foreach}{else}<tr><td colspan="6"><div class="table-empty-state"><strong>Nenhum ponto encontrado nesse período.</strong></div></td></tr>{/if}</tbody></table></div></article>
</section>
