<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<header class="topbar"><button class="icon-button mobile-menu-button" id="mobileMenuButton" type="button" aria-label="Abrir menu" aria-controls="sidebar"><svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><div><p class="eyebrow">Relatórios</p><h1>Condutores</h1></div></header>
<section class="page-body tracking-page report-driver-page">
<form method="get" class="tracking-filters report-filters"><div class="form-field"><label>Condutor *</label><select name="condutor" required><option value="">Selecione um condutor</option>{foreach $condutores as $c}<option value="{$c.con_id}" {if $condutor_selecionado==$c.con_id}selected{/if}>{$c.con_nome|escape} - {$c.con_placa|escape}</option>{/foreach}</select></div>
<div class="form-field"><label>Data inicial</label><input type="date" name="data_inicio" value="{$data_inicio}"></div><div class="form-field"><label>Hora inicial</label><input type="time" name="hora_inicio" value="{$hora_inicio}"></div>
<div class="form-field"><label>Data final</label><input type="date" name="data_fim" value="{$data_fim}"></div><div class="form-field"><label>Hora final</label><input type="time" name="hora_fim" value="{$hora_fim}"></div>
<div class="form-field"><label>Valor por km (R$)</label><input type="number" name="valor_km" value="{$valor_km_input}" min="0" step="0.01"></div><button class="primary-button" type="submit">Calcular</button></form>
<div class="tracking-actions"><div><strong>{$nome_condutor|default:'Selecione um condutor'|escape} {if $placa_condutor}- {$placa_condutor|escape}{/if}</strong><span>{$data_inicio|date_format:"%d/%m/%Y"} {$hora_inicio} até {$data_fim|date_format:"%d/%m/%Y"} {$hora_fim}</span></div><button class="secondary-button" id="openReportPopup" type="button">Exportar PDF</button></div>
<div class="tracking-stats report-stats"><article><span>Pontos GPS</span><strong>{$total_pontos}</strong></article><article><span>Distância percorrida</span><strong>{$distancia_km} km</strong></article><article><span>Velocidade média</span><strong>{$velocidade_media} km/h</strong></article><article><span>Valor por km</span><strong>R$ {$valor_km}</strong></article><article class="report-total-card"><span>Valor calculado</span><strong>R$ {$valor_total}</strong></article></div>
<article class="tracking-map-card"><div class="dashboard-section-title"><div><p class="eyebrow">Trajeto calculado</p><h2>Mapa do período pesquisado</h2></div></div><div id="reportTrackingMap"></div><script id="reportTrackingPoints" type="application/json">{$pontos_json nofilter}</script></article>
</section>
<div class="popup" id="reportExportPopup" aria-hidden="true"><div class="popup__dialog report-popup" role="dialog" aria-modal="true"><button class="popup__close close-report-popup" type="button">×</button><span class="popup__icon popup__icon--info">PDF</span><h3>Montar relatório</h3><p>Escolha os blocos que deseja incluir no arquivo.</p>
<form method="post" action="relatorio_condutores_pdf.php" target="_blank" class="report-options-form">
<input type="hidden" name="condutor" value="{$condutor_selecionado}"><input type="hidden" name="data_inicio" value="{$data_inicio}"><input type="hidden" name="data_fim" value="{$data_fim}"><input type="hidden" name="hora_inicio" value="{$hora_inicio}"><input type="hidden" name="hora_fim" value="{$hora_fim}"><input type="hidden" name="valor_km" value="{$valor_km_input}">
<label><input type="checkbox" name="incluir_cabecalho" value="1" checked><span><strong>Cabeçalho institucional</strong><small>Logo, nome fantasia, CNPJ, e-mail e WhatsApp.</small></span></label>
<label><input type="checkbox" name="incluir_resumo" value="1" checked><span><strong>Resumo do cálculo</strong><small>Período, distância, velocidade, valor por km e total.</small></span></label>
<label><input type="checkbox" name="incluir_mapa" value="1" checked><span><strong>Mapa do trajeto</strong><small>Desenho completo do percurso, com início e fim.</small></span></label>
<label><input type="checkbox" name="incluir_detalhes" value="1"><span><strong>Detalhamento dos pontos</strong><small>Lista de coordenadas e horários registrados.</small></span></label>
<div class="popup__actions"><button class="secondary-button close-report-popup" type="button">Cancelar</button><button class="primary-button" type="submit">Gerar PDF</button></div></form></div></div>
